[package]
name = "echo_server"
version = "0.1.0"
edition = "2024"
workspace = "../.."

[dependencies]
build_info = { path = "../../lib/build_info" }

clap = { version = "4.5.59", features = ["derive"] }
const_format = "0.2.35"
figment = { version = "0.10.19", features = ["json", "test"] }
itertools = "0.14.0"
rocket = "0.5.1"
